name: pb_hrsystem
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.24+24

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  workmanager: ^0.5.2
  dio: ^5.7.0
  awesome_dialog: ^3.2.1
  jwt_decoder: ^2.0.1
  device_info_plus: ^10.1.2
  qr_flutter: ^4.1.0
  flutter_pdfview: ^1.3.2
  simple_animations: ^3.1.1
  web_socket_channel: ^3.0.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  intl: any
  flutter_localization: ^0.2.2
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  table_calendar: ^3.1.2
  local_auth: ^2.2.0
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.2.1
  responsive_framework: ^0.1.0
  shared_preferences: ^2.2.3
  convex_bottom_bar: ^3.2.0
  share_plus: ^10.0.2
  flutter_staggered_grid_view: ^0.7.0
  simple_timetable: ^1.0.3
  dart_date: ^1.4.0
  path_provider: ^2.1.3
  dotted_border: ^2.1.0
  saver_gallery: ^3.0.5
  cross_file: ^0.3.4+1
  flutter_image_compress: ^2.3.0
  flutter_background: ^1.3.0+1
  image_picker: ^1.1.2
  timezone: ^0.9.0
  device_preview: ^1.2.0
  flutter_slidable: ^3.1.1
  fluttertoast: ^8.2.6
  uuid: ^4.4.2
  file_picker: ^8.0.6
  visibility_detector: ^0.2.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.1
  my_device_info_plus: ^0.0.6
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  flutter_timetable: ^1.1.6
  timetable: ^1.0.0-alpha.14
  photo_view: ^0.15.0
  multi_image_picker_view: ^1.1.0
  calendar_day_view: ^3.3.2
  syncfusion_flutter_calendar: ^26.2.13
  flutter_spinkit: ^5.2.1
  timetable_view: ^0.3.0
  board_datetime_picker: ^2.1.5
  flutter_week_view: ^1.3.0
  syncfusion_flutter_datagrid: ^26.2.13
  location: ^6.0.2
  connectivity_plus: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.4.0
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+4
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  flutter_offline: ^4.0.0
  flutter_datetime_format: ^0.0.1
  advanced_calendar_day_view:
    path: "packages/advanced_calendar_day_view"
  auto_route: ^9.2.2
  day_night_time_picker: ^1.3.1
  custom_refresh_indicator: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.1.7
  intl_generator: any
  hive_generator: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/background.png
    - assets/logo.png
    - assets/notification_image.png
    - assets/location_image.png
    - assets/camera_image.png
    - assets/ready_image.png
    - assets/ready_bg.png
    - assets/home_banner.png
    - assets/profile_picture.png
    - assets/qr_code.png
    - assets/darkbg.png
    - assets/bg_2.png
    - assets/success_icon.png
    - assets/banner1.png
    - assets/banner2.png
    - assets/banner3.png
    - assets/flags/english.png
    - assets/flags/laos.png
    - assets/flags/chinese.png
    - assets/avatar_placeholder.png
    - assets/data-2.png
    - assets/firstline.png
    - assets/people.png
    - assets/shop-add.png
    - assets/status-up.png
    - assets/Vector.png
    - assets/Vector-1.png
    - assets/Vector-2.png
    - assets/layer.png
    - assets/element-plus.png
    - assets/playstore.png
    - assets/calendar.png
    - assets/car.png
    - assets/leave_calendar.png
    - assets/cancel.png
    - assets/account_settings.png
    - assets/box-time.png
    - assets/calendar-icon.png
    - assets/title.png
    - assets/task.png
    - assets/android_device.png
    - assets/ios_device.png
    - assets/notification-status.png
    - assets/meeting_room.png
    - assets/car_return.png
    - assets/KPI.png
    - assets/inventory.png
    - assets/lock-circle.png
    - assets/fingerprint.png
